<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$eptloaderimg = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA5JREFUeNpiYAACgAADAAAFAAHbiZPSAAAAAElFTkSuQmCC';
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<img class="photo image"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
	src="<?= $eptloaderimg ?>"
    data-src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
    width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
    height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
    alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>" />
